import sys
sys.path.insert(0,'/Users/ilya/Documents/GitHub/School/Softwere dev./python/Leren-programen/Python/Module2/robotarm')
from RobotArm import RobotArm
from basic import challenges
robotArm = RobotArm(challenges[3],3)
robotArm.grab()
robotArm.moveRight()
robotArm.drop()
robotArm.moveLeft()
robotArm.grab()
for i in range (2): robotArm.moveRight()
robotArm.drop()
robotArm.moveLeft()
robotArm.grab()
robotArm.moveLeft()
robotArm.drop()
for i in range(2): robotArm.moveRight()
robotArm.grab()
for i in range(2): robotArm.moveLeft()
robotArm.drop()
robotArm.report()
