naam =input('Hallo, wat is je naam? ')
leeftijd = input(f'Hi {naam}, hoe oud ben je? ')
gerecht = input(f'En als {leeftijd}, wat eet je het liefst? ' )
drankje = input(f'En wat drinkt het liefst bij {gerecht}? ')
print(f'De {leeftijd}  jarige {naam} drinkt het liefst {drankje} bij {gerecht}.')